export interface MediaTrackJSON {
  '@type': string;
  '@typeorder'?: string;

  // General
  Count?: string | number;
  Status?: string;
  StreamCount?: string | number;
  StreamKind?: string;
  StreamKind_String?: string;
  StreamKindID?: string | number;
  StreamKindPos?: string | number;
  StreamOrder?: string;
  FirstPacketOrder?: string;
  Inform?: string;
  ID?: string;
  OriginalSourceMedium_ID?: string;
  UniqueID?: string;
  UniqueID_String?: string;
  MenuID?: string;
  GeneralCount?: string | number;
  VideoCount?: string | number;
  AudioCount?: string | number;
  TextCount?: string | number;
  OtherCount?: string | number;
  ImageCount?: string | number;
  MenuCount?: string | number;
  Video_Format_List?: string;
  Video_Format_WithHint_List?: string;
  Video_Language_List?: string;
  Audio_Format_List?: string;
  Audio_Format_WithHint_List?: string;
  Audio_Language_List?: string;
  Audio_Channels_Total?: string | number;
  Text_Format_List?: string;
  Text_Format_WithHint_List?: string;
  Text_Language_List?: string;
  Other_Format_List?: string;
  Other_Format_WithHint_List?: string;
  Other_Language_List?: string;
  Image_Format_List?: string;
  Image_Format_WithHint_List?: string;
  Image_Language_List?: string;
  Menu_Format_List?: string;
  Menu_Format_WithHint_List?: string;
  Menu_Language_List?: string;
  CompleteName?: string;
  FolderName?: string;
  FileNameExtension?: string;
  FileName?: string;
  File_Name?: string;
  FileExtension?: string;
  CompleteName_Last?: string;
  FolderName_Last?: string;
  FileNameExtension_Last?: string;
  FileName_Last?: string;
  FileExtension_Last?: string;
  Format?: string;
  Format_String?: string;
  Format_Info?: string;
  'Format/Info'?: string;
  Format_Url?: string;
  Format_Extensions?: string;
  Format_Commercial?: string;
  Format_Commercial_IfAny?: string;
  Format_Version?: string;
  Format_Profile?: string;
  Format_Level?: string;
  Format_Compression?: string;
  Format_Settings?: string;
  Format_AdditionalFeatures?: string;
  InternetMediaType?: string;
  CodecID?: string;
  CodecID_Info?: string;
  CodecID_Hint?: string;
  CodecID_Url?: string;
  CodecID_Description?: string;
  CodecID_Version?: string;
  CodecID_Compatible?: string;
  Interleaved?: string;
  FileSize?: string | number;
  FileSize_String?: string;
  FileSize_String1?: string;
  FileSize_String2?: string;
  FileSize_String3?: string;
  FileSize_String4?: string;
  Archive_Name?: string;
  Archive_Sizing_Status?: 'verified' | 'estimated';
  Archive_Sizing_Source?:
    | 'zip-local-header'
    | 'zip-central-directory'
    | 'tar-header'
    | 'unknown';
  Archive_Sizing_Warning?: string;
  Duration?: string | number;
  Duration_String?: string;
  Duration_String1?: string;
  Duration_String2?: string;
  Duration_String3?: string;
  Duration_String4?: string;
  Duration_String5?: string;
  Duration_Start?: string;
  Duration_End?: string;
  OverallBitRate_Mode?: string;
  OverallBitRate_Mode_String?: string;
  OverallBitRate?: string | number;
  OverallBitRate_String?: string;
  OverallBitRate_Minimum?: string | number;
  OverallBitRate_Nominal?: string | number;
  OverallBitRate_Maximum?: string | number;
  FrameRate?: string | number;
  FrameRate_String?: string;
  FrameRate_Num?: string;
  FrameRate_Den?: string;
  FrameCount?: string | number;
  Delay?: string | number;
  Delay_Settings?: string;
  Delay_DropFrame?: string;
  Delay_Source?: string;
  StreamSize?: string | number;
  StreamSize_String?: string;
  StreamSize_Proportion?: string;
  StreamSize_Demuxed?: string;
  HeaderSize?: string | number;
  DataSize?: string | number;
  FooterSize?: string | number;
  IsStreamable?: string;
  Album_ReplayGain_Gain?: string | number;
  Album_ReplayGain_Peak?: string | number;
  Encryption?: string;
  Encryption_Format?: string;
  Encryption_Length?: string;
  Encryption_Method?: string;
  Encryption_Mode?: string;
  Encryption_Padding?: string;
  Encryption_InitializationVector?: string;
  UniversalAdID_Registry?: string;
  UniversalAdID_Value?: string;
  Title?: string;
  Title_More?: string;
  Domain?: string;
  Collection?: string;
  Season?: string;
  Season_Position?: string;
  Season_Position_Total?: string;
  Movie?: string;
  Movie_More?: string;
  Album?: string;
  Album_More?: string;
  Comic?: string;
  Comic_More?: string;
  Comic_Position_Total?: string;
  Part?: string;
  Part_Position?: string;
  Part_Position_Total?: string;
  Reel?: string;
  Reel_Position?: string;
  Reel_Position_Total?: string;
  Track?: string;
  Track_More?: string;
  PackageName?: string;
  Grouping?: string;
  Chapter?: string;
  SubTrack?: string;
  Original_Album?: string;
  Original_Movie?: string;
  Original_Part?: string;
  Original_Track?: string;
  Compilation?: string;
  Performer?: string;
  Original_Performer?: string;
  Accompaniment?: string;
  Composer?: string;
  Arranger?: string;
  Lyricist?: string;
  Original_Lyricist?: string;
  Conductor?: string;
  Director?: string;
  CoDirector?: string;
  AssistantDirector?: string;
  DirectorOfPhotography?: string;
  SoundEngineer?: string;
  ArtDirector?: string;
  ProductionDesigner?: string;
  Choreographer?: string;
  CostumeDesigner?: string;
  Actor?: string;
  Actor_Character?: string;
  WrittenBy?: string;
  ScreenplayBy?: string;
  EditedBy?: string;
  CommissionedBy?: string;
  Producer?: string;
  CoProducer?: string;
  ExecutiveProducer?: string;
  MusicBy?: string;
  DistributedBy?: string;
  OriginalSourceForm_DistributedBy?: string;
  MasteredBy?: string;
  EncodedBy?: string;
  RemixedBy?: string;
  ProductionStudio?: string;
  ThanksTo?: string;
  Publisher?: string;
  Label?: string;
  Genre?: string;
  PodcastCategory?: string;
  Mood?: string;
  ContentType?: string;
  Subject?: string;
  Description?: string;
  Keywords?: string;
  Summary?: string;
  Synopsis?: string;
  Period?: string;
  LawRating?: string;
  LawRating_Reason?: string;
  ICRA?: string;
  Released_Date?: string;
  Original_Released_Date?: string;
  Recorded_Date?: string;
  Encoded_Date?: string;
  Tagged_Date?: string;
  Written_Date?: string;
  Mastered_Date?: string;
  File_Created_Date?: string;
  File_Created_Date_Local?: string;
  File_Modified_Date?: string;
  File_Modified_Date_Local?: string;
  Recorded_Location?: string;
  Written_Location?: string;
  Archival_Location?: string;
  Encoded_Application?: string;
  Encoded_Application_String?: string;
  Encoded_Application_CompanyName?: string;
  Encoded_Application_Name?: string;
  Encoded_Application_Version?: string;
  Encoded_Application_Url?: string;
  Encoded_Library?: string;
  Encoded_Library_String?: string;
  Encoded_Library_CompanyName?: string;
  Encoded_Library_Name?: string;
  Encoded_Library_Version?: string;
  Encoded_Library_Date?: string;
  Encoded_Library_Settings?: string;
  Encoded_OperatingSystem?: string;
  Encoded_OperatingSystem_CompanyName?: string;
  Encoded_OperatingSystem_Name?: string;
  Encoded_OperatingSystem_Version?: string;
  Encoded_Hardware?: string;
  Encoded_Hardware_CompanyName?: string;
  Encoded_Hardware_Name?: string;
  Encoded_Hardware_Model?: string;
  Encoded_Hardware_Version?: string;
  Cropped?: string;
  Dimensions?: string;
  DotsPerInch?: string;
  Lightness?: string;
  OriginalSourceMedium?: string;
  OriginalSourceForm?: string;
  OriginalSourceForm_NumColors?: string;
  OriginalSourceForm_Name?: string;
  OriginalSourceForm_Cropped?: string;
  OriginalSourceForm_Sharpness?: string;
  Tagged_Application?: string;
  BPM?: string;
  ISRC?: string;
  ISBN?: string;
  ISAN?: string;
  BarCode?: string;
  LCCN?: string;
  UMID?: string;
  CatalogNumber?: string;
  LabelCode?: string;
  Owner?: string;
  Copyright?: string;
  Producer_Copyright?: string;
  TermsOfUse?: string;
  ServiceName?: string;
  ServiceChannel?: string;
  ServiceProvider?: string;
  ServiceType?: string;
  NetworkName?: string;
  OriginalNetworkName?: string;
  Country?: string;
  TimeZone?: string;
  Cover?: string;
  Cover_Description?: string;
  Cover_Type?: string;
  Cover_Mime?: string;
  Cover_Data?: string;
  Lyrics?: string;
  Comment?: string;
  Rating?: string;
  Added_Date?: string;
  Played_First_Date?: string;
  Played_Last_Date?: string;
  Played_Count?: string;
  EPG_Positions_Begin?: string;
  EPG_Positions_End?: string;

  // Video
  Format_Tier?: string;
  MultiView_BaseProfile?: string;
  MultiView_Count?: string;
  MultiView_Layout?: string;
  HDR_Format?: string;
  HDR_Format_String?: string;
  HDR_Format_Commercial?: string;
  HDR_Format_Version?: string;
  HDR_Format_Profile?: string;
  HDR_Format_Level?: string;
  HDR_Format_Settings?: string;
  HDR_Format_Compression?: string;
  HDR_Format_Compatibility?: string;
  Format_Settings_BVOP?: string;
  Format_Settings_QPel?: string;
  Format_Settings_GMC?: string;
  Format_Settings_Matrix?: string;
  Format_Settings_Matrix_Data?: string;
  Format_Settings_CABAC?: string;
  Format_Settings_RefFrames?: string;
  Format_Settings_Pulldown?: string;
  Format_Settings_Endianness?: string;
  Format_Settings_Packing?: string;
  Format_Settings_FrameMode?: string;
  Format_Settings_GOP?: string;
  Format_Settings_PictureStructure?: string;
  Format_Settings_Wrapping?: string;
  Format_Settings_SliceCount?: string;
  MuxingMode?: string;
  Duration_FirstFrame?: string | number;
  Duration_LastFrame?: string | number;
  Source_Duration?: string | number;
  Source_Duration_FirstFrame?: string | number;
  Source_Duration_LastFrame?: string | number;
  BitRate_Mode?: string;
  BitRate_Mode_String?: string;
  BitRate?: string | number;
  BitRate_String?: string;
  BitRate_Minimum?: string | number;
  BitRate_Nominal?: string | number;
  BitRate_Maximum?: string | number;
  BitRate_Encoded?: string | number;
  Width?: string | number;
  Width_String?: string;
  Width_Offset?: string | number;
  Width_Original?: string | number;
  Width_CleanAperture?: string | number;
  Height?: string | number;
  Height_String?: string;
  Height_Offset?: string | number;
  Height_Original?: string | number;
  Height_CleanAperture?: string | number;
  Stored_Width?: string | number;
  Stored_Height?: string | number;
  Sampled_Width?: string | number;
  Sampled_Height?: string | number;
  PixelAspectRatio?: string | number;
  PixelAspectRatio_Original?: string | number;
  PixelAspectRatio_CleanAperture?: string | number;
  DisplayAspectRatio?: string | number;
  DisplayAspectRatio_String?: string;
  DisplayAspectRatio_Original?: string | number;
  DisplayAspectRatio_CleanAperture?: string | number;
  ActiveFormatDescription?: string;
  ActiveFormatDescription_MuxingMode?: string;
  Active_Width?: string | number;
  Active_Height?: string | number;
  Active_DisplayAspectRatio?: string | number;
  Rotation?: string | number;
  FrameRate_Mode?: string;
  FrameRate_Mode_String?: string;
  FrameRate_Mode_Original?: string;
  FrameRate_Minimum?: string | number;
  FrameRate_Nominal?: string | number;
  FrameRate_Maximum?: string | number;
  FrameRate_Original?: string | number;
  FrameRate_Original_Num?: string | number;
  FrameRate_Original_Den?: string | number;
  FrameRate_Real?: string | number;
  Source_FrameCount?: string;
  Standard?: string;
  ColorSpace?: string;
  ChromaSubsampling?: string;
  ChromaSubsampling_String?: string;
  ChromaSubsampling_Position?: string;
  BitDepth?: string | number;
  BitDepth_String?: string;
  BitsPixel_Frame?: string | number;
  ScanType?: string;
  ScanType_Original?: string;
  ScanType_StoreMethod?: string;
  ScanType_StoreMethod_FieldsPerBlock?: string;
  ScanOrder?: string;
  ScanOrder_Stored?: string;
  ScanOrder_StoredDisplayedInverted?: string;
  ScanOrder_Original?: string;
  Compression_Mode?: string;
  Compression_Mode_String?: string;
  Compression_Ratio?: string | number;
  TimeStamp_FirstFrame?: string;
  TimeCode_FirstFrame?: string;
  TimeCode_LastFrame?: string;
  TimeCode_DropFrame?: string;
  TimeCode_Settings?: string;
  TimeCode_Source?: string;
  Gop_OpenClosed?: string;
  Gop_OpenClosed_FirstFrame?: string;
  Source_StreamSize?: string | number;
  Source_StreamSize_Proportion?: string;
  StreamSize_Encoded?: string | number;
  StreamSize_Encoded_Proportion?: string;
  Source_StreamSize_Encoded?: string | number;
  Source_StreamSize_Encoded_Proportion?: string;
  Alignment?: string;
  Language?: string;
  Language_String?: string;
  Language_More?: string;
  ServiceKind?: string;
  Disabled?: string;
  Default?: string;
  Forced?: string;
  AlternateGroup?: string;
  BufferSize?: string | number;
  colour_description_present?: string;
  colour_description_present_Source?: string;
  colour_description_present_Original?: string;
  colour_description_present_Original_Source?: string;
  colour_range?: string;
  colour_range_Source?: string;
  colour_range_Original?: string;
  colour_range_Original_Source?: string;
  colour_primaries?: string;
  colour_primaries_Source?: string;
  colour_primaries_Original?: string;
  colour_primaries_Original_Source?: string;
  transfer_characteristics?: string;
  transfer_characteristics_Source?: string;
  transfer_characteristics_Original?: string;
  transfer_characteristics_Original_Source?: string;
  matrix_coefficients?: string;
  matrix_coefficients_Source?: string;
  matrix_coefficients_Original?: string;
  matrix_coefficients_Original_Source?: string;
  MasteringDisplay_ColorPrimaries?: string;
  MasteringDisplay_ColorPrimaries_Source?: string;
  MasteringDisplay_ColorPrimaries_Original?: string;
  MasteringDisplay_ColorPrimaries_Original_Source?: string;
  MasteringDisplay_Luminance?: string;
  MasteringDisplay_Luminance_Source?: string;
  MasteringDisplay_Luminance_Min?: string;
  MasteringDisplay_Luminance_Max?: string;
  MasteringDisplay_Luminance_Original?: string;
  MasteringDisplay_Luminance_Original_Source?: string;
  MasteringDisplay_Luminance_Original_Min?: string;
  MasteringDisplay_Luminance_Original_Max?: string;
  MaxCLL?: string;
  MaxCLL_Source?: string;
  MaxCLL_Original?: string;
  MaxCLL_Original_Source?: string;
  MaxFALL?: string;
  MaxFALL_Source?: string;
  MaxFALL_Original?: string;
  MaxFALL_Original_Source?: string;

  // Audio
  Format_Settings_SBR?: string;
  Format_Settings_PS?: string;
  Format_Settings_Mode?: string;
  Format_Settings_ModeExtension?: string;
  Format_Settings_Emphasis?: string;

  Format_Settings_Floor?: string;
  Format_Settings_Firm?: string;
  Format_Settings_Sign?: string;
  Format_Settings_Law?: string;
  Format_Settings_ITU?: string;
  Matrix_Format?: string;
  MuxingMode_MoreInfo?: string;
  'Channel(s)'?: string | number;
  'Channel(s)_String'?: string;
  Channels?: string | number;
  Channels_String?: string;
  ChannelPositions?: string;
  ChannelPositions_Original?: string;
  ChannelLayout?: string;
  ChannelLayout_Original?: string;
  ChannelLayoutID?: string;
  SamplesPerFrame?: string;
  SamplingRate?: string | number;
  SamplingRate_String?: string;
  SamplingCount?: string | number;
  Source_SamplingCount?: string | number;
  BitDepth_Detected?: string | number;
  BitDepth_Stored?: string | number;
  Delay_Original?: string | number;
  Delay_Original_Settings?: string;
  Delay_Original_DropFrame?: string;
  Delay_Original_Source?: string;
  Video_Delay?: string | number;
  ReplayGain_Gain?: string | number;
  ReplayGain_Peak?: string | number;
  Interleave_VideoFrames?: string;
  Interleave_Duration?: string;
  Interleave_Preload?: string;

  // Text
  Duration_Start2End?: string;
  Duration_Start_Command?: string;
  Duration_End_Command?: string;
  Duration_Base?: string;
  ElementCount?: string;
  TimeCode_MaxFrameNumber?: string;
  TimeCode_MaxFrameNumber_Theory?: string;
  Events_Total?: string;
  Events_MinDuration?: string;
  Events_PopOn?: string;
  Events_RollUp?: string;
  Events_PaintOn?: string;
  Lines_Count?: string;
  Lines_MaxCountPerEvent?: string;
  Lines_MaxCharacterCount?: string;
  FirstDisplay_Delay_Frames?: string;
  FirstDisplay_Type?: string;

  // Menu
  List_StreamKind?: string;
  List_StreamPos?: string;
  List?: string;
  Countries?: string;
  TimeZones?: string;
  Chapters_Pos_Begin?: string;
  Chapters_Pos_End?: string;

  // Extra (for Chapters, AC-4, MPEG-H, Dolby Atmos data)
  extra?: MediaTrackExtra;

  // Allow any other field from MediaInfo (dynamic nature)
  [key: string]: unknown;
}

/**
 * Signal Group structure for AC-4/MPEG-H audio
 */
export interface SignalGroupEntry {
  Type?: string;
  NumberOfObjects?: string;
  NumberOfObjects_String?: string;
  Channels?: string | number;
  Channels_String?: string;
  BedChannelConfiguration?: string;
  Language_String?: string;
  Language?: string;
  Classifier?: string;
  Format_Profile?: string;
  ChannelMode?: string;
  LinkedTo_Group_Pos?: string;
  Pos?: string;
  Index?: string;
  [key: string]: unknown;
}

/**
 * Presentation structure for AC-4/MPEG-H audio
 */
export interface PresentationEntry {
  PresentationID?: string;
  PresentationLevel?: string;
  ChannelMode?: string;
  DolbyAtmos?: string;
  DialogueNormalization?: string;
  IntegratedLoudness_Speech?: string;
  IntegratedLoudness_Level?: string;
  RealtimeLoudnessCorrected?: string;
  Eac3DrcProfile?: string;
  HomeTheaterAvr?: string;
  FlatPanelTv?: string;
  PortableSpeakers?: string;
  PortableHeadphones?: string;
  LoRoCenterMixGain?: string;
  LoRoSurroundMixGain?: string;
  LtRtCenterMixGain?: string;
  LtRtSurroundMixGain?: string;
  LfeMixGain?: string;
  PreferredDownmix?: string;
  ContentClassifier?: string;
  Language_String?: string;
  Classifier?: string;
  [key: string]: unknown;
}

/**
 * Typed extra fields for MediaTrack
 * Contains known fields from AC-4, MPEG-H, Dolby Atmos, etc.
 */
export interface MediaTrackExtra {
  // Dolby Atmos / Object Audio
  NumberOfDynamicObjects?: string | number;
  NumberOfObjects?: string | number;
  NumberOfObjects_String?: string;
  SignalGroup?: SignalGroupEntry[];
  Presentation?: PresentationEntry[];

  // Delay / Timing
  Source_Delay?: string | number;
  Source_Delay_String?: string;
  Source_Delay_Source?: string;

  // Loudness / Normalization
  dialnorm?: string | number;
  dialnorm_String?: string;
  DialogueNormalization?: string;
  IntegratedLoudness_Speech?: string;
  IntegratedLoudness_Level?: string;
  RealtimeLoudnessCorrected?: string;
  SamplePeakLevel?: string;
  Loudness_Anchor?: string;
  Loudness_Program?: string;
  Loudness_Count?: string;
  AudioLoudnessStandard?: string;
  DialogueCorrected?: string;

  // Codec Configuration
  CodecConfigurationBox?: string;

  // AC-4 / MPEG-H Specific
  PresentationID?: string;
  ChannelMode?: string;
  DolbyAtmos?: string;
  SignalGroupCount?: string | number;
  NumberOfSubstreams?: string | number;
  ChannelCoded?: string;
  DialogueEnhancement?: string;
  MaxGain?: string;

  // DRC (Dynamic Range Compression)
  DrcSets_Count?: string;
  DrcSets_Effects?: string;
  Eac3DrcProfile?: string;
  HomeTheaterAvr?: string;
  FlatPanelTv?: string;
  PortableSpeakers?: string;
  PortableHeadphones?: string;

  // Downmix Settings
  LoRoCenterMixGain?: string;
  LoRoSurroundMixGain?: string;
  LtRtCenterMixGain?: string;
  LtRtSurroundMixGain?: string;
  LfeMixGain?: string;
  PreferredDownmix?: string;

  // Other metadata
  ContentClassifier?: string;
  bitstream_version?: string;
  PresentationLevel?: string;

  // Allow other unknown fields for forward compatibility
  [key: string]: unknown;
}

export interface MediaInfoJSON {
  media?: {
    track: MediaTrackJSON[];
  };
  creatingLibrary?: {
    name: string;
    version: string;
    url: string;
  };
}
